---
- name: Deploy local Node.js app to remote Ubuntu server
  hosts: webservers
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    - name: Install build tools
      apt:
        name: build-essential
        state: present

    - name: Create app directory
      file:
        path: "{{ app_remote_path }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy app files to server
      copy:
        src: "{{ app_local_path }}/"
        dest: "{{ app_remote_path }}/"
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Install npm dependencies
      npm:
        path: "{{ app_remote_path }}"
        production: no

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: Start app with pm2
      shell: |
        pm2 start app.js --name "{{ pm2_app_name }}"
        pm2 save
        pm2 startup systemd -u ubuntu --hp /home/ubuntu
      args:
        chdir: "{{ app_remote_path }}"
        executable: /bin/bash
