name: Deploy Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add sshkey from github secrets
        run: echo "${{ secrets.AWS_KEY }}" > aws.key
      - name: Read key 
        run:  chmod 600 aws.key
      - name: Run Ansible
        run: | 
            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts.ini node.yml